security:
  oauth2:
    client:
      clientId: spend-money-service
      clientSecret: ${SPEND_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    cassandra:
      keyspace-name: spend_money
      contactPoints: cassandradb
      port: 9042
      schemaAction: CREATE_IF_NOT_EXISTS

server:
  servlet:
    context-path: /expenses
  port: 6000

feign:
  hystrix:
    enabled: true
